<?php
/**
 * Created by PhpStorm.
 * User: Root
 * Date: 18.08.2017
 * Time: 00:07
 */

namespace app\components;
use yii\base\Widget;

use app\models\Category;


class MenuWidget extends Widget
{
    public $tpl;
    public $data;
    public $tree;
    public $menuHtml;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->tpl===null){
            $this->tpl='menu';
        }
        $this->tpl.='.php';
    }


    public function rand_ar(){

        $ar=[];
        for ($i=0;$i<10;$i++){
            $ar[$i]=[
                'id_cat'=>$i,
//                'parent_cat'=>rand(0, 15),
                'parent_cat'=>0,

            ];

        }
        for ($i=10;$i<200;$i++){
            $ar[$i]=[
                'id_cat'=>$i,
                'parent_cat'=>rand(0, 15),
//                'parent_cat'=>0,

            ];

        }
        return $ar;
    }


    public function run()
    {

        //get cache
        $menu = \Yii::$app->cache->get('menu');
        if ($menu) return $menu;

        $this->data=$this->rand_ar();

       // p($this->data);

        $this->tree = $this->getTree();
        $this->menuHtml = $this->getMenuHtml($this->tree);

//        p($this->tree);

        \Yii::$app->cache->set('menu', $this->menuHtml, 1);
        return $this->menuHtml;
//            return $this->data;

    }

    protected function getTree(){
        $tree=[];
        $ii=1;
        foreach ($this->data as $id=>&$node){


            if(!$node['parent_cat']){


                $tree[$id]=&$node;
                $ii=1;
            } else {

                $this->data[$node['parent_cat']]['childs'][$node['id_cat']]=&$node;

           $ii++; }

        }


        return $tree;
    }

    protected function getMenuHtml($tree){
        $str='';
        foreach ($tree as $category){
            $str.=$this->catToTemplate($category);
        }
        return $str;
    }

    protected function catToTemplate($category){
        ob_start();
        include __DIR__.'/menu_tpl/'.$this->tpl;
        return ob_get_clean();
    }



}
